### ISSUE TITLE
Libprotoident development status

### ISSUE THREAD

**Issue by vpiserchia** [wanduow/libprotoident#12]
Hello everyone,

first of all, thank you for this project! My question is about the future plan of it? Do you have any roadmap and/or more publication to share about the project and its status and plan?

thank you and best regards
vito piserchia

**Comment by salcock** [comment]
Hello,

Actually, we're not far away from a new release (2.0.8) which will add rules for nearly 70 completely new protocols and improve the rules for another 25 or so. The only thing really left to do prior to release is run our normal pre-release tests, but you can preview the new version by checking out the 'develop' branch of the code.

In a more general sense, libprotoident is more of a side project for our research group because our current research grants require us to work on other projects. As a result, we will continue to maintain and promote libprotoident, but we can't really afford to dedicate too much time towards active development. Development work is usually pretty sporadic and is mostly dependant on me having a bit of spare time or a burning question that I really want to answer. For example, most of the 2.0.8 development was the result of me wondering how much non-HTTP traffic we see on TCP port 80 and what that traffic actually is.

So there's no real roadmap or plan to speak of, but I'm really proud of libprotoident and will continue to support and occasionally add new rules to it for as long as I can. One thing that can help is if people who are using libprotoident and are finding it useful could email us at contact@wand.net.nz and let us know more about what you are using libprotoident for. If we know that people are using it, it is easier to justify spending more time on libprotoident development.
